USE_WEBUI: True
USE_NOVELAI: True
WEBUI_URI: http://localhost:15000
GENERATED_IMAGE_OUTDIR: generated_files
ADMIN_IDS: []
ALLOWED_GUILD_IDS: []
DEFAULT_NEGATIVE_PROMPT: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry
STEPS:
  DEFAULT: 20
  MAXIMUM: 30
MESSAGE:
  RESPONSE:
    - 画像を生成しています
    - ちょっと待っててね
  STEPS:
    - <0>ステップで作成しています
