USE_WEBUI: True
USE_NOVELAI: True
LOCALE: ja
WEBUI_URI: http://localhost:15000
GENERATED_IMAGE_OUTDIR: generated_files
USE_GOOGLE_TRANS: False
GOOGLE_TRANS_PROJECT_ID: none
ADMIN_IDS: []
ALLOWED_GUILD_IDS: []
DEFAULT_NEGATIVE_PROMPT: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry
STEPS: [1, 30, 20] # min, max, default
SCALE: [1, 20, 11]
WIDTH: [64, 1024, 512]
HEIGHT: [64, 1024, 768]
BATCH_SIZE: [1, 4, 1]
NSFW_EXCLUDE:
  [
    "nsfw",
    "nude",
    "fuck",
    "fucked",
    "nipples",
    "vagina",
    "spread legs",
    "penis",
    "breasts",
    "pantyshot",
  ]
ELEMENTAL_CODE_JSON_PATH: elemental_code/json
