USE_WEBUI: True
USE_NOVELAI: True
WEBUI_URI: http://localhost:15000
GENERATED_IMAGE_OUTDIR: generated_files
ADMIN_IDS: []
ALLOWED_GUILD_IDS: []
DEFAULT_NEGATIVE_PROMPT: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry
STEPS:
  DEFAULT: 20
  MAXIMUM: 30
SCALE:
  DEFAULT: 11
  MAXIMUM: 20
SIZE:
  WIDTH:
    DEFAULT: 512
    MAXIMUM: 1024
  HEIGHT:
    DEFAULT: 768
    MAXIMUM: 1024
BATCH_SIZE:
  DEFAULT: 1
  MAXIMUM: 4
MESSAGE:
  RESPONSE:
    - 画像を生成しています
    - ちょっと待っててね
  STEPS:
    - <0>ステップで作成しています
  BRACKET:
    - あと、\{\}は()に置き換えました
